### ISSUE TITLE
Fails right after brand new installation of 0.10.11 version

### ISSUE THREAD

**Issue by tarys** [datacontract/datacontract-cli#400]
Steps to reproduce:

1. Create brand new virtual env:
   ```pyenv virtualenv 3.12 myproject```
2. Run:
    ```pip install datacontract-cli==0.10.11```
3. Run:
    ```datacontract```

Expected result:
Help message is printed.

Actual result:
```
Traceback (most recent call last):
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/bin/datacontract", line 5, in <module>
    from datacontract.cli import app
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/lib/python3.12/site-packages/datacontract/cli.py", line 15, in <module>
    from datacontract import web
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/lib/python3.12/site-packages/datacontract/web.py", line 7, in <module>
    from datacontract.data_contract import DataContract, ExportFormat
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/lib/python3.12/site-packages/datacontract/data_contract.py", line 16, in <module>
    from datacontract.engines.soda.check_soda_execute import check_soda_execute
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/lib/python3.12/site-packages/datacontract/engines/soda/check_soda_execute.py", line 11, in <module>
    from datacontract.engines.soda.connections.duckdb import get_duckdb_connection
  File "/Users/taras/.pyenv/versions/3.12.2/envs/consent-service/lib/python3.12/site-packages/datacontract/engines/soda/connections/duckdb.py", line 3, in <module>
    from deltalake import DeltaTable
ModuleNotFoundError: No module named 'deltalake'
```

**Comment by ryancollingwood** [comment]
Are you running MacOS? I had the same issue on fresh install.

I was also having the same issue when just trying to import the module on it's own
```python
from deltalake import DeltaTable
```

After some digging I figured the lack of a java runtime might be the issue, so I  installed one
```bash
brew install openjdk@17
```

Closed all my terminal sessions, created a new environment and reinstalled via
```bash
pip install datacontract-cli[all]
```

And then was able import it on it's own
```
from deltalake import DeltaTable
```

However trying to run the datacontract command still returns the error
```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/datacontract", line 5, in <module>
    from datacontract.cli import app
  File "/opt/anaconda3/lib/python3.11/site-packages/datacontract/cli.py", line 15, in <module>
    from datacontract import web
  File "/opt/anaconda3/lib/python3.11/site-packages/datacontract/web.py", line 7, in <module>
    from datacontract.data_contract import DataContract, ExportFormat
  File "/opt/anaconda3/lib/python3.11/site-packages/datacontract/data_contract.py", line 16, in <module>
    from datacontract.engines.soda.check_soda_execute import check_soda_execute
  File "/opt/anaconda3/lib/python3.11/site-packages/datacontract/engines/soda/check_soda_execute.py", line 11, in <module>
    from datacontract.engines.soda.connections.duckdb import get_duckdb_connection
  File "/opt/anaconda3/lib/python3.11/site-packages/datacontract/engines/soda/connections/duckdb.py", line 3, in <module>
    from deltalake import DeltaTable
ModuleNotFoundError: No module named 'deltalake'
```

**Comment by jochenchrist** [comment]
Thanks for reporting. I am working on it.

**Comment by jochenchrist** [comment]
Version [0.10.12](https://github.com/datacontract/datacontract-cli/releases/tag/v0.10.12) released that should solve this issue.
